### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by cheginit** [aaraney/NWM-Dockerized-Job-Scheduler#29]
I have a couple of suggestion ofr your consideration:
- Use `pathlib` instead of `os.path`. Read [here](https://treyhunner.com/2018/12/why-you-should-be-using-pathlib/)
- Using `map` is not always a good idea and it seems that you rely on it in many cases. There have been many discussions on `map` vs list comprehension, for example [here](https://stackoverflow.com/questions/1247486/list-comprehension-vs-map). It seems that list comprehension is faster in many cases.
- setup the `pre-commit` workflow with isort, black, flake8 and mypy, it does wonders!
- setup readthedocs.

**Comment by cheginit** [comment]
I would be happy to help you with implementing these changes if you like.

**Comment by aaraney** [comment]
- Thanks for the comments and suggestions! I greatly appreciate them. Thanks for linking the pathlib article, it along with you later pointed out `map` usage are the achilles heal in my python practices. I just need to break those habits! I will go ahead and open issues for translating code from `os.path` to `pathlib`. 

- Yeahhh, once again you are right. I am just stuck in my ways. I had a class on functional programming and fell in love with methods like `map`, `filter`, and `reduce`. Ill add those as issues too. I agree with the readability of list comprehensions for sure. 

- It would be great to have your help here now that you have some experience with the `pre-commit` workflow. I am an admitted newb when it comes to `isort`, `black`, `mypy`, and even `tox`. Talking through some of that stuff would be really helpful, plus any of it that you would like to have your hand at, you are always welcome.

- I completely agree. Ill move it to an issue. Just haven't gotten around to it
